server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

spring:
  jpa:
    open-in-view: false # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    hibernate:
      ddl-auto: create # todo change in future to not lose data
    properties:
      hibernate:
        show_sql: false # console became super messy
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    password: ""
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver



#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: example@gmail.com
#    password: examplepassword
#    properties:
#      mail:
#        smtp:
#          timeout: 5000
#          writetimeout: 5000
#          auth: true
#          connectiontimeout: 5000
#          starttls:
#            enable: true
#            required: true