spring:
  jpa:
    hibernate:
      ddl-auto: create # todo change in future to not lose data
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    password: ""
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver